// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddobogrglnyrhlbubxpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkb2JvZ3JnbG55cmhsYnVieHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDk5NDUsImV4cCI6MjA2NTIyNTk0NX0.c0UWZOOiS1ngmxvlmw2f-hHT7bchEod0rHPQHKkHOwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);